version: '3'
services:
  backend:
    network_mode: "bridge"
    # build: ./django
    container_name: wagtail_grapple
    image: ghcr.io/cividi/wagtail_grapple:latest
    ports:
      - "8000:8000"
    volumes:
      - ./django:/app
    stdin_open: true